### ISSUE TITLE
maxCardsPerStack

### ISSUE THREAD

**Issue by olsins** [motey/MMM_ncdeck#1]
Hey! Thanks for the great module - all in all it works fine.
I just have an issue with the
maxCardsPerStack: 
It seems, that ist does not have any effekt?

Thanks for any help!

here ist the config

{
      module: "MMM_ncdeck",
      position: "bottom_bar",
      config: {
        nextcloud: {
          host: „XXX“,
          user: „XXX“,
          pass: „XXX“
        },
        updateIntervalSec: 60,
        deckBoardId: 3,
        maxCardsPerStack: 4,
        hideStacks: [""],
        coloredHeader: false,
        simpleLayout: true,
        complexLayout: {
          coloredLabels: false,
          showLabels: true,
          showAssignedUser: false
        }
      }
    },

**Comment by motey** [comment]
Hi @olsins ,
thanks for the feedback. I will have a look into it. Stay tuned.

**Comment by motey** [comment]
Seems like `maxCardsPerStack` was accidentally dropped when i did a refactoring.
now its working again.

**Comment by olsins** [comment]
Perfect! Thx- I will try it out!
