### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by Alxcsa** [motey/MMM_ncdeck#2]
Hi,
Thank you for your module for Nextcloud Deck.
With my Nextcloud server in version 18.0.4, I need to change a path in node_helper.js
Here is the change line 4
`const api_base_url = '/index.php/apps/deck/api/v1.0'`
Regards
Alex

**Comment by motey** [comment]
Hi @Alxcsa,
thanks for the feedback. Oddly for me the old  `api_base_url` value worked with 18.0.4 and the recent Deck app. But as your proposal reflects the [documentary](https://github.com/nextcloud/deck/blob/master/docs/API.md#prequisited) and seems to work for my instance as well i changed it accordingly to your feedback.
Regards, Tim
