### ISSUE TITLE
Module does not work with 2 factor authorization

### ISSUE THREAD

**Issue by marcelverdult** [motey/MMM_ncdeck#6]
hi,
the module does not work with 2 factor authorization. Is there any way to make it work? Running public nextcloud without it is no option.

greets

Marcel

**Comment by motey** [comment]
Hi Marcel,
thanks for the feedback.
no, 2 factor authorization is not implemented and i am not planning on doing so. This is a tiny sparetime project for me and for now, i only invest time in features i would use myself. Hope you understand.
But I would be happy to receive any pull request and/or support you in implementing 2 factor authorization in MMM_ncdeck.

**Comment by motey** [comment]
When thinking about it i have no idea how one would implement a feature like this. You would need to use the nextcloud auth-flow and therefore interact with your magicmirror. You can only provide static config to the modules. 
@marcelverdult  Do you have any thoughts on this?

Did you give it a try via a custom device password?
https://docs.nextcloud.com/server/stable/user_manual/en/session_management.html#managing-devices

**Comment by marcelverdult** [comment]
the device password solved the issue! thx a lot!
