### ISSUE TITLE
Deck won't show up

### ISSUE THREAD

**Issue by djzwerg** [motey/MMM_ncdeck#7]
Thanks for this module. But when I try to use it the deck won't be shown. The parameters are correct but it shows only "Loading deck from [URL]".

Edit: Maybe there is something wrong with that repo? I wasn't able to use `git clone git@github.com:motey/MMM_ncdeck.git` because of missing permissions. So I used `git clone https://github.com/motey/MMM_ncdeck.git`.

**Comment by djzwerg** [comment]
`npm install` seems to failed in my first try. Now everything works fine.

**Comment by motey** [comment]
> Maybe there is something wrong with that repo? I wasn't able to use git clone git@github.com:motey/MMM_ncdeck.git because of missing permissions. So I used git clone https://github.com/motey/MMM_ncdeck.git.

Sounds like you need to setup your Device to work with github https://docs.github.com/en/authentication/connecting-to-github-with-ssh
