### ISSUE TITLE
remove this obsolete app from apps.nextcloud.com please

### ISSUE THREAD

**Issue by p-bo** [motey/MMM_ncdeck#8]
Hello,
would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove your past app:

https://apps.nextcloud.com/apps/mmm_ncdeck

and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?

Thanks and have a nice day

**Comment by motey** [comment]
Hello @p-bo,
what brings you to the conclusion that this app is obsolete? It works and i use it every day.
Thanks and have a nice day

**Comment by motey** [comment]
Also:

> most importantly it clutters apps catalogue in every Nextcloud instance

Is this true? mmm_ncdeck runs under "integrations" and therefore wont appear in an Nextclouds instance app catalogue as far as i can see. Its not an Nextcloud app but an app that connects to a Nextcloud(/deck app) instance.

**Comment by p-bo** [comment]
@motey Sorry, my fault - disregard please.
