### ISSUE TITLE
Deck not loading with seemingly correct config

### ISSUE THREAD

**Issue by bigrjsuto** [motey/MMM_ncdeck#9]
```js
{
  module: "MMM_ncdeck",
  position: "bottom_center",
  config: {
    nextcloud: {
      host: "https://cloud.xxxxxx.com/",
      user: "xxxxxx",
      pass: "xxxxxx",
    },
    updateIntervalSec: 30,
    deckBoardId: 1,
    hideStacks: ["Done"],
    coloredHeader: false,
    simpleLayout: true,
    complexLayout: {
      coloredLabels: false,
      showLabels: true,
      showAssignedUser: true
    },
    maxCardsPerStack: 3
  }
}
```
Just shows loading.
![Screenshot from 2023-11-20 22-42-48](https://github.com/motey/MMM_ncdeck/assets/13565841/c3c9fea3-cd3c-4ca5-bdef-ec0050852cb2)

**Comment by motey** [comment]
Hi @bigrjsuto, 
(you are allowed to greet the people that write your open source code for free :) )
last time i went into this code is some days ago.
As a shot in the dark: try to remove the trailing / from `host: "https://cloud.xxxxxx.com/"` so you have `host: "https://cloud.xxxxxx.com"`

**Comment by bigrjsuto** [comment]
Thanks for the response. removing the "/" didn't seem to make a difference. Same thing as before.

**Comment by motey** [comment]
Based on the details you've shared, it's a bit tricky to figure out the exact problem, but I'm leaning towards it being related to your Nextcloud setup.
Some more shots in the dark:
*  What kind of user-backend are you using? Any SSO or 2FA stuff like SAML, OIDC, Social Login or TOTP? If so, you might need an "[App Token](https://docs.nextcloud.com/server/stable/user_manual/en/session_management.html#managing-devices)" from your Nextcloud.
* Also, do you happen to have a self-signed cert for your Nextcloud setup? That could mess with machine-to-machine connections.

To dig deeper and give better help, you need to share more information.
Have you checked your Magic Mirror server logs or the web console in your browser for any related errors?

Just a heads-up: Running a MagicMirror (in particular with modules and connecting it to other selfhosted system) can be a bit of a journey. you need a certain drive to have fun hacking.
Based on the sparse information you provided, i am not sure if you're new to this or just looking for a quick fix. If you're new, I'm totally up giving a certain amount of help. But if you're after a speedy solution, maybe there's a better fit out there for you.

**Comment by bigrjsuto** [comment]
I've tried using the App Password within NC. No luck.
I'm running Nextcloud behind an nginxproxymanager LXC on Proxmox. This is a MagicMirror LXC from https://tteck.github.io/Proxmox/ on the same Proxmox.

Because of NPM it directs to the domain so I can't use the local IP if that would have worked. 

This would be my 2nd MagicMirror and I want it to solely run ncdeck so I can see at my desk a small screen always showing what I have going on. I really like the idea of using your NCDeck module because it would use the screen real estate most efficiently, as compared to a tasks module which would just show a vertical list.

I've been using MagicMirror for probably 4 years now. Running Nextcloud for probably 6. 

I spent countless hours building a MM screen displaying a highly modified MMM-CalendarExt2 as the main focus.

I'm not good with programming but I'm stubborn and always will to learn. Google/github/stackoverflow/reddit/etc have been invaluable to me for learning how to setup all kinds of things. I've been flashing Android ROMs, modding 3D printers + firmware, first Ubuntu server w/ Nextcloud, Plex, & -arr apps, now running Proxmox + TrueNAS VM + Windows VM.

Note: this MagicMirror LXC doesn't have pm2 installed, so I'm not sure how to get logs.

**Comment by bigrjsuto** [comment]
I installed ncdeck onto my current MagicMirror setup and it works! I'm trying to compare config files and make this ncdeck MM the same as my OG MM, but I still can't see to get the ncdeck MM to work.

**Comment by motey** [comment]
> I installed ncdeck onto my current MagicMirror setup and it works! 

Happy to hear that! Keep digging!

>  this MagicMirror LXC doesn't have pm2 installed, so I'm not sure how to get logs.

I am more of a docker type :) so i cant really give you any directions here. But i am 100% there are logs in LXC somewhere and i am pretty sure the logs contain the information we need.  Thorough log reading solves 75%-90% of all computer problems ;D 
You don't want to poke system until anything happens, you want to measure whats wrong and adapt your system.

Did you have a look at the client side logs via Browser Dev tools? Maybe this also contains some useful hints
https://support.iterable.com/hc/en-us/articles/115001674223-Developer-tools-in-Chrome-and-Firefox
In particular if there are any messages in the "Console" or some non 2xx web requests in the "Network"-Tab.

**Comment by bigrjsuto** [comment]
Browser console. I never thought of that.
Here are the errors I see:
```
Firefox can’t establish a connection to the server at ws://192.168.1.197:8080/socket.io/?EIO=4&transport=websocket&sid=NYbJm6Iqq9geBuAxAAB0.
```
```
The resource from “http://192.168.1.197:8080/css/custom.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```
192.168.1.197 is the IP of my MagicMirror LXC

**Comment by motey** [comment]
https://github.com/MichMich/MagicMirror/issues/1597
https://forum.magicmirror.builders/topic/13545/run-mm-on-w10-to-test-modules-404-and-x-content-type-options-nosniff/2

maybe just a missing `npm install`?

I will close the issue here for now, as it seems not to be a ncdeck problem, but a MM configuration/setup issue.
And it seems[ you allready made ncdeck running](https://github.com/motey/MMM_ncdeck/issues/9#issuecomment-1821468902) :) 
If it turns out to be something different, keep commenting here. maybe it will help someone else in future or i can provide another hint.
good luck and have a good one mate!

**Comment by bigrjsuto** [comment]
Thanks for your help and patience. Great module you got here.

**Comment by bigrjsuto** [comment]
The issue was something with the MagicMirror LXC for Proxmox I was trying to use.
I instead created a blank Debian LXC, then installed MagicMirror. Now it works.
